# Generated by Django 5.1.1 on 2024-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=255)),
                ('deal_type', models.CharField(max_length=50)),
                ('deal_name', models.CharField(max_length=255)),
                ('price_range', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
